language: rust
rust: stable

cache: cargo

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - rustup component add clippy
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test

before_deploy:
  - cargo doc --no-deps --lib

deploy:
  provider: pages
  overwrite: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: rust-spandex/spandex
  target_branch: gh-pages
  local_dir: target/doc/
  on:
    branch: master

